-- Keep business IDs and all existing references; only the internal primary key changes.
ALTER TABLE orders ADD COLUMN row_id UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE orders ADD CONSTRAINT ux_order_business_id UNIQUE (id);

-- Rebind existing foreign keys to the business-ID unique constraint. Preserve their
-- actual definitions instead of assuming the names generated by earlier migrations.
CREATE TEMP TABLE order_reference_definitions ON COMMIT DROP AS
SELECT conrelid::regclass::text AS referencing_table, conname, pg_get_constraintdef(oid) AS definition
FROM pg_constraint WHERE contype = 'f' AND confrelid = 'orders'::regclass;

DO $$
DECLARE reference RECORD; primary_name TEXT;
BEGIN
    FOR reference IN SELECT * FROM order_reference_definitions LOOP
        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', reference.referencing_table, reference.conname);
    END LOOP;
    SELECT conname INTO STRICT primary_name FROM pg_constraint
        WHERE contype = 'p' AND conrelid = 'orders'::regclass;
    EXECUTE format('ALTER TABLE orders DROP CONSTRAINT %I', primary_name);
    ALTER TABLE orders ADD PRIMARY KEY (row_id);
    FOR reference IN SELECT * FROM order_reference_definitions LOOP
        EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s',
            reference.referencing_table, reference.conname, reference.definition);
    END LOOP;
END $$;

-- Reopening allows multiple ACCEPTED, ABORTED and OPEN checkpoints for one task.
ALTER TABLE order_checkpoints DROP CONSTRAINT ux_order_checkpoint;
CREATE INDEX ix_order_checkpoint_timeline ON order_checkpoints(order_id, occurred_at DESC);

CREATE TABLE order_courier_attempts (
    id UUID PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL REFERENCES orders(id),
    requester_id VARCHAR(128) NOT NULL,
    courier_id VARCHAR(128) NOT NULL,
    item_description VARCHAR(100) NOT NULL,
    pickup_supplier_id VARCHAR(128) NOT NULL,
    delivery_supplier_id VARCHAR(128) NOT NULL,
    offered_credits BIGINT NOT NULL,
    delivery_time_limit_minutes INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    aborted_at TIMESTAMPTZ NOT NULL,
    order_version BIGINT NOT NULL,
    original_order_id VARCHAR(36),
    reposted_order_id VARCHAR(36),
    CONSTRAINT ux_courier_attempt_order_version UNIQUE (order_id, order_version)
);
CREATE INDEX ix_courier_attempt_timeline ON order_courier_attempts(courier_id, aborted_at DESC);

-- Preserve recoverable historical expired aborts before normalizing current state.
-- Earlier unexpired cancellations emitted no ABORTED checkpoint and cannot be reconstructed.
INSERT INTO order_courier_attempts
    (id, order_id, requester_id, courier_id, item_description, pickup_supplier_id, delivery_supplier_id,
     offered_credits, delivery_time_limit_minutes, created_at, expires_at, aborted_at, order_version,
     original_order_id, reposted_order_id)
SELECT gen_random_uuid(), o.id, o.requester_id, c.actor_id, o.item_description,
       o.pickup_supplier_id, o.delivery_supplier_id, o.offered_credits, o.delivery_time_limit_minutes,
       o.created_at, o.expires_at, c.occurred_at, o.version, o.original_order_id, o.reposted_order_id
FROM orders o JOIN LATERAL (
    SELECT actor_id, occurred_at FROM order_checkpoints
    WHERE order_id = o.id AND status = 'ABORTED' AND actor_id IS NOT NULL
    ORDER BY occurred_at DESC LIMIT 1
) c ON TRUE WHERE o.status = 'ABORTED';

UPDATE orders SET status = 'EXPIRED', courier_id = NULL WHERE status = 'ABORTED';
