import { test, expect } from "@playwright/test"

test("post, browse, accept and deliver without login", async ({ page }, testInfo) => {
  const description = `Collect lunch ${Date.now()} ${testInfo.project.name}`
  await page.goto("/requests/new")
  await expect(page.getByRole("heading", { name: "Post a request" })).toBeVisible()
  await page.getByLabel("What do you need?").fill(description)
  await page.getByLabel("Pickup", { exact: true }).click()
  await page.getByRole("option", { name: "Campus canteen (demo)" }).click()
  await page.getByLabel("Delivery", { exact: true }).click()
  await page.getByRole("option", { name: "Library (demo)" }).click()
  const singaporeExpiry = new Date(Date.now() + 10 * 60 * 60 * 1000).toISOString().slice(0, 16)
  await page.getByLabel("Accept before (Singapore time)").fill(singaporeExpiry)
  await page.getByRole("button", { name: "Post request", exact: true }).click()
  await expect(page).toHaveURL(/\/requests\/[a-f0-9-]+$/)
  await expect(page.getByText("OPEN", { exact: true })).toBeVisible()
  await page.getByRole("link", { name: "Browse errands", exact: true }).click()
  const card = page.getByRole("article").filter({ hasText: description })
  await expect(card).toBeVisible()
  await page.getByLabel("Demo courier ID").fill("demo-requester")
  await expect(card.getByRole("button", { name: "Your request" })).toBeDisabled()
  await page.getByLabel("Demo courier ID").fill("demo-courier")
  await card.getByRole("button", { name: "Accept errand" }).click()
  await expect(page).toHaveURL(/\/errands\/[a-f0-9-]+\?actor=/)
  await expect(page.getByRole("button", { name: "Start delivery" })).toBeVisible()
  await page.getByLabel("Demo courier ID").fill("someone-else")
  await expect(page.getByRole("button", { name: "Start delivery" })).toBeDisabled()
  await page.getByLabel("Demo courier ID").fill("demo-courier")
  await page.getByRole("button", { name: "Start delivery" }).click()
  await page.getByRole("button", { name: "Mark picked up" }).click()
  await page.getByRole("button", { name: "Mark delivered" }).click()
  await expect(page.getByRole("status").filter({ hasText: "Delivery recorded" })).toBeVisible()
  await page.reload()
  await expect(page.getByRole("list", { name: "Delivery progress" }).getByRole("listitem")).toHaveCount(4)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("delivery.png"), fullPage: true })
})

test("dependency error is shown and can be retried", async ({ page }) => {
  await page.route("**/api/orders/errands?*", route => route.fulfill({ status: 503, contentType: "application/json",
    body: JSON.stringify({ status: 503, error: "SERVICE_UNAVAILABLE", message: "Order service unavailable." }) }))
  await page.goto("/errands")
  const error = page.getByRole("alert").filter({ hasText: "Order service unavailable." })
  await expect(error).toBeVisible()
  await page.unroute("**/api/orders/errands?*")
  await page.getByRole("button", { name: "Try again" }).click()
  await expect(error).toHaveCount(0)
})
