package sg.edu.nus.foc.supplier.supplier;

import java.time.Instant;

/**
 * A campus store, facility or landmark used as an errand pickup or delivery point.
 *
 * @param id            generated by the service, never reused (F1.1.1)
 * @param active        only active suppliers can be chosen for new errands (F1.3.2)
 * @param source        whether the record came from the seed file or an administrator
 * @param seedKey       natural key of the seed row that created the record, so the row still finds it after
 *                      an administrator renames it; null for records created by administrators
 * @param adminModified an administrator has edited or deactivated the record, so the seed loader leaves it alone
 */
public record Supplier(
        String id,
        SupplierDetails details,
        boolean active,
        SupplierSource source,
        String seedKey,
        boolean adminModified,
        Instant createdAt,
        Instant updatedAt) {

    /** The seed loader may change this record: it created it and no administrator has changed it since (F2.4). */
    public boolean managedBySeed() {
        return source == SupplierSource.SEED && !adminModified;
    }

    /** This record after an administrator's edit; from then on the seed loader never overwrites it. */
    public Supplier editedByAdmin(SupplierDetails newDetails, boolean newActive) {
        return new Supplier(id, newDetails, newActive, source, seedKey, true, createdAt, updatedAt);
    }

    /** This record with the details of its seed row; the row's natural key becomes the seed key. */
    public Supplier seededWith(SupplierDetails newDetails) {
        return new Supplier(id, newDetails, active, source, newDetails.naturalKey(), adminModified, createdAt,
                updatedAt);
    }

    /** This record deactivated by the seed loader because its row left the seed file. */
    public Supplier deactivatedBySeed() {
        return new Supplier(id, details, false, source, seedKey, adminModified, createdAt, updatedAt);
    }

    /** This record as last written at {@code instant}. */
    public Supplier updatedAt(Instant instant) {
        return new Supplier(id, details, active, source, seedKey, adminModified, createdAt, instant);
    }
}
