package sg.edu.nus.foc.supplier.supplier;

import java.time.Instant;

/**
 * A campus store, facility or landmark used as an errand pickup or delivery point.
 *
 * @param id     generated by the service, never reused (F1.1.1)
 * @param active only active suppliers can be chosen for new errands (F1.3.2)
 * @param source whether the record came from the seed file or an administrator
 */
public record Supplier(
        String id,
        SupplierDetails details,
        boolean active,
        SupplierSource source,
        Instant createdAt,
        Instant updatedAt) {
}
