spring:
  mongodb:
    auto-index-creation: true
    uri: mongodb+srv://ohyixian_db_user:9XIUEEvlU2BFxBvA@userservicedb.ix8vfjz.mongodb.net/UserServiceDB?retryWrites=true&w=majority
  application:
    name: userservice
  mvc:
    problemdetails:
      enabled: true

server:
  port: ${PORT:8080}
